### ISSUE TITLE
Key binding 'h' overrides special-mode binding

### ISSUE THREAD

**Issue by lassik** [srfi-explorations/emacs-srfi#4]
`srfi-mode` is derived from `special-mode`; in the keymap of the latter mode, `h` (for "help") is bound to `describe-mode`. We should probably not override that binding in `srfi-mode`.

Ref 0e3ddd6

**Comment by lassik** [comment]
@arthurgleckler Since `h` is the standard help key, should we pick another binding for the landing page? For example, `l` (lowercase letter ell) is free.

Do you use the landing pages a lot even from Emacs with one-key shortcuts to the discussion and repo readily available? If they are special-purpose, we can also preserve the command without a key binding, in which case it needs to be run with `M-x`.

**Comment by arthurgleckler** [comment]
On Sun, Jun 28, 2020 at 10:06 AM Lassi Kortela <notifications@github.com>
wrote:

> @arthurgleckler <https://github.com/arthurgleckler> Since h is the
> standard help key, should we pick another binding for the landing page? For
> example, l (lowercase letter ell) is free.
>
Good point.  That would be fine.

> Do you use the landing pages a lot even from Emacs with one-key shortcuts
> to the discussion and repo readily available? If they are special-purpose,
> we can also preserve the command without a key binding, in which case it
> needs to be run with M-x.
>
Yeah, I use it when checking that the landing page has been generated
properly, e.g. after adding See-also links.

**Comment by lassik** [comment]
> Yeah, I use it when checking that the landing page has been generated properly, e.g. after adding See-also links.

Right. If you want the `l` key, please make a commit to that effect :)

**Comment by lassik** [comment]
Fixed in commit 041430e
